-- Incident Open Backlog Query
-- Retrieves all open incidents for RF, Field Ops, and Switch categories
-- Joins with site, ring, market, user, and group data

SELECT *
FROM BDM_ITSM_REPORTING_DB.SN_ITSM_REPORTING_V.V_INCIDENT_ALL INC
LEFT JOIN BDM_NDW_NTWK_SITE_DEVELOPMENT_DB.MAGENTABUILT_REFERENCE_V.V_SITE_TRACKER S
    ON SPLIT_PART(INC.CONFIG_ITEM, '_', 1) = S.SITE_ID
LEFT JOIN BDM_NDW_NTWK_SITE_DEVELOPMENT_DB.MAGENTABUILT_REFERENCE_V.V_RING_TRACKER R
    ON S.RING_ID = R.RING_ID
LEFT JOIN BDM_NDW_NTWK_SITE_DEVELOPMENT_DB.MAGENTABUILT_REFERENCE_V.V_MARKET_TRACKER MKT
    ON R.MARKET_ID = MKT.MARKET_ID
LEFT JOIN BDM_ITSM_REPORTING_DB.SN_ITSM_REPORTING_V.V_SYS_USER U
    ON INC.ASSIGNED_TO = U.NAME
LEFT JOIN BDM_ITSM_REPORTING_DB.SN_ITSM_REPORTING_V.V_SYS_USER_GROUP AG
    ON INC.ASSIGNMENT_GROUP = AG.NAME
LEFT JOIN BDM_NDW_IDENTIFY_MANAGEMENT_DB.PROFILEMANAGER_V.V_GROUP G
    ON INC.ASSIGNMENT_GROUP = G.GROUP_NAME
WHERE UPPER(G.CATEGORY) IN ('RF', 'FIELD OPS', 'SWITCH')
  AND INC.RESOLVED_DATE IS NULL
  AND INC.state NOT IN ('Resolved', 'Closed', 'Terminated', 'Canceled')
  AND incident_number NOT IN ('INC113904146')
  AND U_FULLFILLMENT_SYSTEM = 'ServiceNow'
