-- Incident Open Backlog Query
-- Retrieves all open incidents for RF, Field Ops, and Switch categories
-- Joins with site, ring, market, user, and group data
-- Note: Specific columns selected to avoid sensitive PII

SELECT
    -- Incident fields
    INC.INCIDENT_NUMBER,
    INC.STATE,
    INC.PRIORITY,
    INC.CATEGORY,
    INC.SUBCATEGORY,
    INC.SHORT_DESCRIPTION,
    INC.DESCRIPTION,
    INC.OPENED_DATE,
    INC.RESOLVED_DATE,
    INC.CLOSED_DATE,
    INC.ASSIGNMENT_GROUP,
    INC.ASSIGNED_TO,
    INC.CONFIG_ITEM,
    INC.IMPACT,
    INC.URGENCY,
    INC.SEVERITY,
    INC.U_FULLFILLMENT_SYSTEM,
    INC.SYS_CLASS_NAME,
    INC.COMMENTS_AND_WORK_NOTES,
    INC.RESOLUTION_CODE,
    INC.RESOLUTION_NOTES,
    
    -- Site fields
    S.SITE_ID,
    S.S_SITE_NAME,
    S.S_SITE_STATUS,
    S.S_SITE_CLASS,
    S.S_CITY,
    S.S_STATE,
    S.S_SITE_LATITUDE,
    S.S_SITE_LONGITUDE,
    
    -- Ring fields
    R.RING_ID,
    R.R_RING_NAME,
    R.R_RING_STATUS,
    
    -- Market fields
    MKT.MARKET_ID,
    MKT.M_MARKET_ABBREVATION,
    MKT.M_AREA,
    MKT.REGION_ID,
    MKT.RGN_RGN_ABBRV,
    
    -- Group fields (non-PII)
    G.CATEGORY AS GROUP_CATEGORY,
    G.GROUP_TYPE
FROM BDM_ITSM_REPORTING_DB.SN_ITSM_REPORTING_V.V_INCIDENT_ALL INC
LEFT JOIN BDM_NDW_NTWK_SITE_DEVELOPMENT_DB.MAGENTABUILT_REFERENCE_V.V_SITE_TRACKER S
    ON SPLIT_PART(INC.CONFIG_ITEM, '_', 1) = S.SITE_ID
LEFT JOIN BDM_NDW_NTWK_SITE_DEVELOPMENT_DB.MAGENTABUILT_REFERENCE_V.V_RING_TRACKER R
    ON S.RING_ID = R.RING_ID
LEFT JOIN BDM_NDW_NTWK_SITE_DEVELOPMENT_DB.MAGENTABUILT_REFERENCE_V.V_MARKET_TRACKER MKT
    ON R.MARKET_ID = MKT.MARKET_ID
LEFT JOIN BDM_NDW_IDENTIFY_MANAGEMENT_DB.PROFILEMANAGER_V.V_GROUP G
    ON INC.ASSIGNMENT_GROUP = G.GROUP_NAME
WHERE UPPER(G.CATEGORY) IN ('RF', 'FIELD OPS', 'SWITCH')
  AND INC.RESOLVED_DATE IS NULL
  AND INC.state NOT IN ('Resolved', 'Closed', 'Terminated', 'Canceled')
  AND incident_number NOT IN ('INC113904146')
  AND U_FULLFILLMENT_SYSTEM = 'ServiceNow'
